### ISSUE TITLE
AttributeError: 'Forecast' object has no attribute 'daily'

### ISSUE THREAD

**Issue by Antyteza** [thsis/boston_weather#1]
Hi,

maybe there's been a change in the DS API, but as i replicate the code I get an error from the topic title... any idea what might be wrong?

**Comment by thsis** [comment]
Hey,

it should be fixed now. The Darksky devs changed the way their API works. Before you could access the interesting bits as attributes, (i.e. you could get away with something like `boston.daily`). Now they changed it, so you can index the interesting fields like in a dictionary (i.e. you have to do `boston["daily"]["data"]`).

I have no idea why they did this. I'm sure it has a reason.

If you don't mind, might I ask what you are doing with this? I wrote this stuff a year ago  for university and since then ain't no one ever showed interest in that :)

Anyway, if you still have problems just let me know

**Comment by Antyteza** [comment]
It works, thanks!

I'm working on an econometric model and need ~2 years of daily weather data for 20 European cities. I used to work with Wunderground API, but it's been dead for a couple of months...

Now I will have to transfer F's to Celsius and find a way to scrap all the cities at once. :)

**Comment by thsis** [comment]
Coolio, good luck with that :)
